#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : compat-gnome-bluetooth-soname-13
Version  : 3.34.5
Release  : 26
URL      : https://download.gnome.org/sources/gnome-bluetooth/3.34/gnome-bluetooth-3.34.5.tar.xz
Source0  : https://download.gnome.org/sources/gnome-bluetooth/3.34/gnome-bluetooth-3.34.5.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: compat-gnome-bluetooth-soname-13-lib = %{version}-%{release}
Requires: compat-gnome-bluetooth-soname-13-license = %{version}-%{release}
Requires: compat-gnome-bluetooth-soname-13-locales = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : dbus-python
BuildRequires : glibc-bin
BuildRequires : gobject-introspection-dev
BuildRequires : pkgconfig(libcanberra-gtk3)
BuildRequires : pkgconfig(libnotify)

%description
# GNOME Bluetooth
gnome-bluetooth is collection of widgets for applications that want
to select Bluetooth devices. It is also used by GNOME session
components such as the Settings and gnome-shell.

%package lib
Summary: lib components for the compat-gnome-bluetooth-soname-13 package.
Group: Libraries
Requires: compat-gnome-bluetooth-soname-13-license = %{version}-%{release}

%description lib
lib components for the compat-gnome-bluetooth-soname-13 package.


%package license
Summary: license components for the compat-gnome-bluetooth-soname-13 package.
Group: Default

%description license
license components for the compat-gnome-bluetooth-soname-13 package.


%package locales
Summary: locales components for the compat-gnome-bluetooth-soname-13 package.
Group: Default

%description locales
locales components for the compat-gnome-bluetooth-soname-13 package.


%prep
%setup -q -n gnome-bluetooth-3.34.5
cd %{_builddir}/gnome-bluetooth-3.34.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1647873237
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs

%install
mkdir -p %{buildroot}/usr/share/package-licenses/compat-gnome-bluetooth-soname-13
cp %{_builddir}/gnome-bluetooth-3.34.5/COPYING %{buildroot}/usr/share/package-licenses/compat-gnome-bluetooth-soname-13/b47456e2c1f38c40346ff00db976a2badf36b5e3
cp %{_builddir}/gnome-bluetooth-3.34.5/COPYING.LIB %{buildroot}/usr/share/package-licenses/compat-gnome-bluetooth-soname-13/545f380fb332eb41236596500913ff8d582e3ead
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang gnome-bluetooth2
## Remove excluded files
rm -f %{buildroot}*/usr/bin/bluetooth-sendto
rm -f %{buildroot}*/usr/include/gnome-bluetooth/bluetooth-chooser-button.h
rm -f %{buildroot}*/usr/include/gnome-bluetooth/bluetooth-chooser-combo.h
rm -f %{buildroot}*/usr/include/gnome-bluetooth/bluetooth-chooser.h
rm -f %{buildroot}*/usr/include/gnome-bluetooth/bluetooth-client.h
rm -f %{buildroot}*/usr/include/gnome-bluetooth/bluetooth-enums.h
rm -f %{buildroot}*/usr/include/gnome-bluetooth/bluetooth-filter-widget.h
rm -f %{buildroot}*/usr/include/gnome-bluetooth/bluetooth-settings-widget.h
rm -f %{buildroot}*/usr/include/gnome-bluetooth/bluetooth-utils.h
rm -f %{buildroot}*/usr/lib64/girepository-1.0/GnomeBluetooth-1.0.typelib
rm -f %{buildroot}*/usr/lib64/libgnome-bluetooth.so
rm -f %{buildroot}*/usr/lib64/pkgconfig/gnome-bluetooth-1.0.pc
rm -f %{buildroot}*/usr/share/applications/bluetooth-sendto.desktop
rm -f %{buildroot}*/usr/share/gir-1.0/GnomeBluetooth-1.0.gir
rm -f %{buildroot}*/usr/share/gnome-bluetooth/pin-code-database.xml
rm -f %{buildroot}*/usr/share/icons/hicolor/16x16/apps/bluetooth.png
rm -f %{buildroot}*/usr/share/icons/hicolor/16x16/status/bluetooth-active.png
rm -f %{buildroot}*/usr/share/icons/hicolor/16x16/status/bluetooth-disabled.png
rm -f %{buildroot}*/usr/share/icons/hicolor/16x16/status/bluetooth-paired.png
rm -f %{buildroot}*/usr/share/icons/hicolor/22x22/apps/bluetooth.png
rm -f %{buildroot}*/usr/share/icons/hicolor/22x22/status/bluetooth-active.png
rm -f %{buildroot}*/usr/share/icons/hicolor/22x22/status/bluetooth-disabled.png
rm -f %{buildroot}*/usr/share/icons/hicolor/22x22/status/bluetooth-paired.png
rm -f %{buildroot}*/usr/share/icons/hicolor/24x24/apps/bluetooth.png
rm -f %{buildroot}*/usr/share/icons/hicolor/24x24/status/bluetooth-active.png
rm -f %{buildroot}*/usr/share/icons/hicolor/24x24/status/bluetooth-disabled.png
rm -f %{buildroot}*/usr/share/icons/hicolor/24x24/status/bluetooth-paired.png
rm -f %{buildroot}*/usr/share/icons/hicolor/32x32/apps/bluetooth.png
rm -f %{buildroot}*/usr/share/icons/hicolor/32x32/status/bluetooth-active.png
rm -f %{buildroot}*/usr/share/icons/hicolor/32x32/status/bluetooth-disabled.png
rm -f %{buildroot}*/usr/share/icons/hicolor/32x32/status/bluetooth-paired.png
rm -f %{buildroot}*/usr/share/icons/hicolor/48x48/apps/bluetooth.png
rm -f %{buildroot}*/usr/share/icons/hicolor/48x48/status/bluetooth-active.png
rm -f %{buildroot}*/usr/share/icons/hicolor/48x48/status/bluetooth-disabled.png
rm -f %{buildroot}*/usr/share/icons/hicolor/scalable/apps/bluetooth.svg
rm -f %{buildroot}*/usr/share/icons/hicolor/scalable/status/bluetooth-paired.svg
rm -f %{buildroot}*/usr/share/man/man1/bluetooth-sendto.1

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgnome-bluetooth.so.13
/usr/lib64/libgnome-bluetooth.so.13.1.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-gnome-bluetooth-soname-13/545f380fb332eb41236596500913ff8d582e3ead
/usr/share/package-licenses/compat-gnome-bluetooth-soname-13/b47456e2c1f38c40346ff00db976a2badf36b5e3

%files locales -f gnome-bluetooth2.lang
%defattr(-,root,root,-)

